const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_PRODUCT = "FETCH_PRODUCT";
const SET_PRODUCT = "SET_PRODUCT";
const FECTH_FEATURED_PRODUCTS = "FECTH_FEATURED_PRODUCTS";
const FECTH_PRODUCT_BYSLUG = "FECTH_PRODUCT_BYSLUG";

export {
  FETCH_PRODUCTS,
  FETCH_PRODUCT,
  SET_PRODUCT,
  FECTH_FEATURED_PRODUCTS,
  FECTH_PRODUCT_BYSLUG,
};
